import { z } from "zod";
export declare const insertUserSchema: z.ZodObject<z.objectUtil.extendShape<Omit<any, "id" | "createdAt" | "updatedAt">, {
    email: z.ZodEffects<z.ZodString, string, string>;
    username: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    password: z.ZodOptional<z.ZodString>;
    googleId: z.ZodOptional<z.ZodString>;
    firstName: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    lastName: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    profileImage: z.ZodOptional<z.ZodString>;
    role: z.ZodDefault<z.ZodEnum<["admin", "staff"]>>;
}>, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    email?: unknown;
    username?: unknown;
    password?: unknown;
    googleId?: unknown;
    firstName?: unknown;
    lastName?: unknown;
    profileImage?: unknown;
    role?: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    email?: unknown;
    username?: unknown;
    password?: unknown;
    googleId?: unknown;
    firstName?: unknown;
    lastName?: unknown;
    profileImage?: unknown;
    role?: unknown;
}>;
export declare const updateUserSchema: z.ZodObject<z.objectUtil.extendShape<{
    [x: string]: z.ZodOptional<any>;
    [x: number]: z.ZodOptional<any>;
    [x: symbol]: z.ZodOptional<any>;
    email: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    username: z.ZodOptional<z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>>;
    password: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    googleId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    firstName: z.ZodOptional<z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>>;
    lastName: z.ZodOptional<z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>>;
    profileImage: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    role: z.ZodOptional<z.ZodDefault<z.ZodEnum<["admin", "staff"]>>>;
}, {
    id: z.ZodString;
}>, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    email?: unknown;
    username?: unknown;
    password?: unknown;
    googleId?: unknown;
    firstName?: unknown;
    lastName?: unknown;
    profileImage?: unknown;
    role?: unknown;
    id?: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    email?: unknown;
    username?: unknown;
    password?: unknown;
    googleId?: unknown;
    firstName?: unknown;
    lastName?: unknown;
    profileImage?: unknown;
    role?: unknown;
    id?: unknown;
}>;
export declare const guestAlertSettingsSchema: z.ZodObject<{
    enabled: z.ZodDefault<z.ZodBoolean>;
    channels: z.ZodDefault<z.ZodArray<z.ZodEnum<["whatsapp", "push"]>, "many">>;
    advanceNotice: z.ZodDefault<z.ZodArray<z.ZodNumber, "many">>;
    lastNotified: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    enabled: boolean;
    channels: ("push" | "whatsapp")[];
    advanceNotice: number[];
    lastNotified?: string | undefined;
}, {
    enabled?: boolean | undefined;
    channels?: ("push" | "whatsapp")[] | undefined;
    advanceNotice?: number[] | undefined;
    lastNotified?: string | undefined;
}>;
export declare const insertGuestSchema: z.ZodObject<z.objectUtil.extendShape<Omit<any, "id" | "checkinTime" | "checkoutTime" | "isCheckedIn" | "profilePhotoUrl" | "alertSettings">, {
    name: z.ZodEffects<z.ZodString, string, string>;
    capsuleNumber: z.ZodString;
    paymentAmount: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    paymentMethod: z.ZodDefault<z.ZodEnum<["cash", "tng", "bank", "platform"]>>;
    paymentCollector: z.ZodEffects<z.ZodString, string, string>;
    isPaid: z.ZodDefault<z.ZodBoolean>;
    notes: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    status: z.ZodOptional<z.ZodEnum<["vip", "blacklisted"]>>;
    expectedCheckoutDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    checkInDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    gender: z.ZodOptional<z.ZodEnum<["male", "female", "other", "prefer-not-to-say"]>>;
    nationality: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    phoneNumber: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    email: z.ZodOptional<z.ZodUnion<[z.ZodEffects<z.ZodString, string, string>, z.ZodLiteral<"">]>>;
    idNumber: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    emergencyContact: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    emergencyPhone: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    age: z.ZodOptional<z.ZodString>;
    profilePhotoUrl: z.ZodOptional<z.ZodAny>;
}>, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    name?: unknown;
    capsuleNumber?: unknown;
    paymentAmount?: unknown;
    paymentMethod?: unknown;
    paymentCollector?: unknown;
    isPaid?: unknown;
    notes?: unknown;
    status?: unknown;
    expectedCheckoutDate?: unknown;
    checkInDate?: unknown;
    gender?: unknown;
    nationality?: unknown;
    phoneNumber?: unknown;
    email?: unknown;
    idNumber?: unknown;
    emergencyContact?: unknown;
    emergencyPhone?: unknown;
    age?: unknown;
    profilePhotoUrl?: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    name?: unknown;
    capsuleNumber?: unknown;
    paymentAmount?: unknown;
    paymentMethod?: unknown;
    paymentCollector?: unknown;
    isPaid?: unknown;
    notes?: unknown;
    status?: unknown;
    expectedCheckoutDate?: unknown;
    checkInDate?: unknown;
    gender?: unknown;
    nationality?: unknown;
    phoneNumber?: unknown;
    email?: unknown;
    idNumber?: unknown;
    emergencyContact?: unknown;
    emergencyPhone?: unknown;
    age?: unknown;
    profilePhotoUrl?: unknown;
}>;
export declare const updateGuestSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    capsuleNumber: z.ZodOptional<z.ZodString>;
    paymentAmount: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    paymentMethod: z.ZodOptional<z.ZodEnum<["cash", "tng", "bank", "platform"]>>;
    paymentCollector: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    isPaid: z.ZodOptional<z.ZodBoolean>;
    notes: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    status: z.ZodEffects<z.ZodOptional<z.ZodEffects<z.ZodUnion<[z.ZodString, z.ZodNull]>, string | null, string | null>>, string | null | undefined, string | null | undefined>;
    expectedCheckoutDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    checkInDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    gender: z.ZodEffects<z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>, string | undefined, string | undefined>;
    nationality: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    phoneNumber: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    email: z.ZodOptional<z.ZodUnion<[z.ZodEffects<z.ZodString, string, string>, z.ZodLiteral<"">]>>;
    idNumber: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    emergencyContact: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    emergencyPhone: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    age: z.ZodOptional<z.ZodString>;
    profilePhotoUrl: z.ZodOptional<z.ZodAny>;
    alertSettings: z.ZodOptional<z.ZodEffects<z.ZodString, string | undefined, string>>;
}, "strip", z.ZodTypeAny, {
    name?: string | undefined;
    nationality?: string | undefined;
    idNumber?: string | undefined;
    phoneNumber?: string | undefined;
    email?: string | undefined;
    expectedCheckoutDate?: string | undefined;
    capsuleNumber?: string | undefined;
    paymentAmount?: string | undefined;
    paymentMethod?: "cash" | "tng" | "bank" | "platform" | undefined;
    paymentCollector?: string | undefined;
    isPaid?: boolean | undefined;
    notes?: string | undefined;
    gender?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    age?: string | undefined;
    profilePhotoUrl?: any;
    status?: string | null | undefined;
    alertSettings?: string | undefined;
    checkInDate?: string | undefined;
}, {
    name?: string | undefined;
    nationality?: string | undefined;
    idNumber?: string | undefined;
    phoneNumber?: string | undefined;
    email?: string | undefined;
    expectedCheckoutDate?: string | undefined;
    capsuleNumber?: string | undefined;
    paymentAmount?: string | undefined;
    paymentMethod?: "cash" | "tng" | "bank" | "platform" | undefined;
    paymentCollector?: string | undefined;
    isPaid?: boolean | undefined;
    notes?: string | undefined;
    gender?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    age?: string | undefined;
    profilePhotoUrl?: any;
    status?: string | null | undefined;
    alertSettings?: string | undefined;
    checkInDate?: string | undefined;
}>;
export declare const checkoutGuestSchema: z.ZodObject<{
    id: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
export declare const bulkGuestImportSchema: z.ZodArray<z.ZodObject<z.objectUtil.extendShape<z.objectUtil.extendShape<Omit<any, "id" | "checkinTime" | "checkoutTime" | "isCheckedIn" | "profilePhotoUrl" | "alertSettings">, {
    name: z.ZodEffects<z.ZodString, string, string>;
    capsuleNumber: z.ZodString;
    paymentAmount: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    paymentMethod: z.ZodDefault<z.ZodEnum<["cash", "tng", "bank", "platform"]>>;
    paymentCollector: z.ZodEffects<z.ZodString, string, string>;
    isPaid: z.ZodDefault<z.ZodBoolean>;
    notes: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    status: z.ZodOptional<z.ZodEnum<["vip", "blacklisted"]>>;
    expectedCheckoutDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    checkInDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    gender: z.ZodOptional<z.ZodEnum<["male", "female", "other", "prefer-not-to-say"]>>;
    nationality: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    phoneNumber: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    email: z.ZodOptional<z.ZodUnion<[z.ZodEffects<z.ZodString, string, string>, z.ZodLiteral<"">]>>;
    idNumber: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    emergencyContact: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    emergencyPhone: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>>;
    age: z.ZodOptional<z.ZodString>;
    profilePhotoUrl: z.ZodOptional<z.ZodAny>;
}>, {
    checkinTime: z.ZodOptional<z.ZodString>;
}>, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    name?: unknown;
    capsuleNumber?: unknown;
    paymentAmount?: unknown;
    paymentMethod?: unknown;
    paymentCollector?: unknown;
    isPaid?: unknown;
    notes?: unknown;
    status?: unknown;
    expectedCheckoutDate?: unknown;
    checkInDate?: unknown;
    gender?: unknown;
    nationality?: unknown;
    phoneNumber?: unknown;
    email?: unknown;
    idNumber?: unknown;
    emergencyContact?: unknown;
    emergencyPhone?: unknown;
    age?: unknown;
    profilePhotoUrl?: unknown;
    checkinTime?: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    name?: unknown;
    capsuleNumber?: unknown;
    paymentAmount?: unknown;
    paymentMethod?: unknown;
    paymentCollector?: unknown;
    isPaid?: unknown;
    notes?: unknown;
    status?: unknown;
    expectedCheckoutDate?: unknown;
    checkInDate?: unknown;
    gender?: unknown;
    nationality?: unknown;
    phoneNumber?: unknown;
    email?: unknown;
    idNumber?: unknown;
    emergencyContact?: unknown;
    emergencyPhone?: unknown;
    age?: unknown;
    profilePhotoUrl?: unknown;
    checkinTime?: unknown;
}>, "many">;
export declare const insertCapsuleSchema: z.ZodObject<z.objectUtil.extendShape<Omit<any, "id">, {
    number: z.ZodEffects<z.ZodString, string, string>;
    section: z.ZodEnum<["back", "middle", "front"]>;
    isAvailable: z.ZodDefault<z.ZodBoolean>;
    cleaningStatus: z.ZodDefault<z.ZodEnum<["cleaned", "to_be_cleaned"]>>;
    toRent: z.ZodDefault<z.ZodBoolean>;
    lastCleanedAt: z.ZodOptional<z.ZodDate>;
    lastCleanedBy: z.ZodOptional<z.ZodString>;
    color: z.ZodOptional<z.ZodString>;
    purchaseDate: z.ZodOptional<z.ZodDate>;
    position: z.ZodOptional<z.ZodEnum<["top", "bottom"]>>;
    remark: z.ZodOptional<z.ZodString>;
    problemDescription: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
}>, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    number?: unknown;
    section?: unknown;
    isAvailable?: unknown;
    cleaningStatus?: unknown;
    toRent?: unknown;
    lastCleanedAt?: unknown;
    lastCleanedBy?: unknown;
    color?: unknown;
    purchaseDate?: unknown;
    position?: unknown;
    remark?: unknown;
    problemDescription?: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    number?: unknown;
    section?: unknown;
    isAvailable?: unknown;
    cleaningStatus?: unknown;
    toRent?: unknown;
    lastCleanedAt?: unknown;
    lastCleanedBy?: unknown;
    color?: unknown;
    purchaseDate?: unknown;
    position?: unknown;
    remark?: unknown;
    problemDescription?: unknown;
}>;
export declare const updateCapsuleSchema: z.ZodObject<{
    number: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    section: z.ZodOptional<z.ZodEnum<["back", "middle", "front"]>>;
    isAvailable: z.ZodOptional<z.ZodBoolean>;
    cleaningStatus: z.ZodOptional<z.ZodEnum<["cleaned", "to_be_cleaned"]>>;
    toRent: z.ZodOptional<z.ZodBoolean>;
    color: z.ZodOptional<z.ZodString>;
    purchaseDate: z.ZodOptional<z.ZodDate>;
    position: z.ZodOptional<z.ZodEnum<["top", "bottom"]>>;
    remark: z.ZodOptional<z.ZodString>;
    problemDescription: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
}, "strip", z.ZodTypeAny, {
    number?: string | undefined;
    section?: "back" | "middle" | "front" | undefined;
    isAvailable?: boolean | undefined;
    cleaningStatus?: "cleaned" | "to_be_cleaned" | undefined;
    toRent?: boolean | undefined;
    color?: string | undefined;
    purchaseDate?: Date | undefined;
    position?: "top" | "bottom" | undefined;
    remark?: string | undefined;
    problemDescription?: string | undefined;
}, {
    number?: string | undefined;
    section?: "back" | "middle" | "front" | undefined;
    isAvailable?: boolean | undefined;
    cleaningStatus?: "cleaned" | "to_be_cleaned" | undefined;
    toRent?: boolean | undefined;
    color?: string | undefined;
    purchaseDate?: Date | undefined;
    position?: "top" | "bottom" | undefined;
    remark?: string | undefined;
    problemDescription?: string | undefined;
}>;
export declare const markCapsuleCleanedSchema: z.ZodObject<{
    capsuleNumber: z.ZodString;
    cleanedBy: z.ZodEffects<z.ZodString, string, string>;
}, "strip", z.ZodTypeAny, {
    capsuleNumber: string;
    cleanedBy: string;
}, {
    capsuleNumber: string;
    cleanedBy: string;
}>;
export declare const loginSchema: z.ZodObject<{
    email: z.ZodEffects<z.ZodString, string, string>;
    password: z.ZodString;
}, "strip", z.ZodTypeAny, {
    email: string;
    password: string;
}, {
    email: string;
    password: string;
}>;
export declare const googleAuthSchema: z.ZodObject<{
    token: z.ZodString;
}, "strip", z.ZodTypeAny, {
    token: string;
}, {
    token: string;
}>;
export declare const createCapsuleProblemSchema: z.ZodObject<{
    capsuleNumber: z.ZodEffects<z.ZodString, string, string>;
    description: z.ZodEffects<z.ZodString, string, string>;
    reportedBy: z.ZodEffects<z.ZodString, string, string>;
}, "strip", z.ZodTypeAny, {
    capsuleNumber: string;
    description: string;
    reportedBy: string;
}, {
    capsuleNumber: string;
    description: string;
    reportedBy: string;
}>;
export declare const resolveProblemSchema: z.ZodObject<{
    resolvedBy: z.ZodEffects<z.ZodString, string, string>;
    notes: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
}, "strip", z.ZodTypeAny, {
    resolvedBy: string;
    notes?: string | undefined;
}, {
    resolvedBy: string;
    notes?: string | undefined;
}>;
export declare const guestSelfCheckinSchema: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodObject<{
    nameAsInDocument: z.ZodEffects<z.ZodString, string, string>;
    phoneNumber: z.ZodEffects<z.ZodString, string, string>;
    gender: z.ZodEnum<["male", "female", "other", "prefer-not-to-say"]>;
    nationality: z.ZodEffects<z.ZodString, string, string>;
    checkInDate: z.ZodEffects<z.ZodString, string, string>;
    checkOutDate: z.ZodEffects<z.ZodString, string, string>;
    icNumber: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, string | undefined, string | undefined>, string | undefined, string | undefined>;
    passportNumber: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, string | undefined, string | undefined>, string | undefined, string | undefined>, string | undefined, string | undefined>, string | undefined, string | undefined>;
    icDocumentUrl: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, string | undefined, string | undefined>;
    passportDocumentUrl: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, string | undefined, string | undefined>;
    paymentMethod: z.ZodEnum<["cash", "bank", "online_platform"]>;
    guestPaymentDescription: z.ZodOptional<z.ZodString>;
    emergencyContact: z.ZodOptional<z.ZodString>;
    emergencyPhone: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}, {
    nationality: string;
    phoneNumber: string;
    paymentMethod: "cash" | "bank" | "online_platform";
    gender: "male" | "female" | "other" | "prefer-not-to-say";
    checkInDate: string;
    nameAsInDocument: string;
    checkOutDate: string;
    notes?: string | undefined;
    emergencyContact?: string | undefined;
    emergencyPhone?: string | undefined;
    icNumber?: string | undefined;
    passportNumber?: string | undefined;
    icDocumentUrl?: string | undefined;
    passportDocumentUrl?: string | undefined;
    guestPaymentDescription?: string | undefined;
}>;
export declare const createTokenSchema: z.ZodEffects<z.ZodObject<{
    capsuleNumber: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    autoAssign: z.ZodOptional<z.ZodBoolean>;
    guestName: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    phoneNumber: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    email: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    expectedCheckoutDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    checkInDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    expiresInHours: z.ZodDefault<z.ZodNumber>;
    guideOverrideEnabled: z.ZodOptional<z.ZodBoolean>;
    guideShowIntro: z.ZodOptional<z.ZodBoolean>;
    guideShowAddress: z.ZodOptional<z.ZodBoolean>;
    guideShowWifi: z.ZodOptional<z.ZodBoolean>;
    guideShowCheckin: z.ZodOptional<z.ZodBoolean>;
    guideShowOther: z.ZodOptional<z.ZodBoolean>;
    guideShowFaq: z.ZodOptional<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    expiresInHours: number;
    phoneNumber?: string | undefined;
    email?: string | undefined;
    expectedCheckoutDate?: string | undefined;
    capsuleNumber?: string | undefined;
    autoAssign?: boolean | undefined;
    guestName?: string | undefined;
    checkInDate?: string | undefined;
    guideOverrideEnabled?: boolean | undefined;
    guideShowIntro?: boolean | undefined;
    guideShowAddress?: boolean | undefined;
    guideShowWifi?: boolean | undefined;
    guideShowCheckin?: boolean | undefined;
    guideShowOther?: boolean | undefined;
    guideShowFaq?: boolean | undefined;
}, {
    phoneNumber?: string | undefined;
    email?: string | undefined;
    expectedCheckoutDate?: string | undefined;
    capsuleNumber?: string | undefined;
    autoAssign?: boolean | undefined;
    guestName?: string | undefined;
    checkInDate?: string | undefined;
    expiresInHours?: number | undefined;
    guideOverrideEnabled?: boolean | undefined;
    guideShowIntro?: boolean | undefined;
    guideShowAddress?: boolean | undefined;
    guideShowWifi?: boolean | undefined;
    guideShowCheckin?: boolean | undefined;
    guideShowOther?: boolean | undefined;
    guideShowFaq?: boolean | undefined;
}>, {
    expiresInHours: number;
    phoneNumber?: string | undefined;
    email?: string | undefined;
    expectedCheckoutDate?: string | undefined;
    capsuleNumber?: string | undefined;
    autoAssign?: boolean | undefined;
    guestName?: string | undefined;
    checkInDate?: string | undefined;
    guideOverrideEnabled?: boolean | undefined;
    guideShowIntro?: boolean | undefined;
    guideShowAddress?: boolean | undefined;
    guideShowWifi?: boolean | undefined;
    guideShowCheckin?: boolean | undefined;
    guideShowOther?: boolean | undefined;
    guideShowFaq?: boolean | undefined;
}, {
    phoneNumber?: string | undefined;
    email?: string | undefined;
    expectedCheckoutDate?: string | undefined;
    capsuleNumber?: string | undefined;
    autoAssign?: boolean | undefined;
    guestName?: string | undefined;
    checkInDate?: string | undefined;
    expiresInHours?: number | undefined;
    guideOverrideEnabled?: boolean | undefined;
    guideShowIntro?: boolean | undefined;
    guideShowAddress?: boolean | undefined;
    guideShowWifi?: boolean | undefined;
    guideShowCheckin?: boolean | undefined;
    guideShowOther?: boolean | undefined;
    guideShowFaq?: boolean | undefined;
}>;
export declare const updateGuestTokenCapsuleSchema: z.ZodEffects<z.ZodObject<{
    capsuleNumber: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    autoAssign: z.ZodOptional<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    capsuleNumber?: string | undefined;
    autoAssign?: boolean | undefined;
}, {
    capsuleNumber?: string | undefined;
    autoAssign?: boolean | undefined;
}>, {
    capsuleNumber?: string | undefined;
    autoAssign?: boolean | undefined;
}, {
    capsuleNumber?: string | undefined;
    autoAssign?: boolean | undefined;
}>;
export declare const insertAdminNotificationSchema: z.ZodObject<Omit<any, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
}>;
export declare const insertPushSubscriptionSchema: z.ZodObject<Omit<any, "id" | "createdAt" | "lastUsed">, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
}>;
export declare const updateSettingsSchema: z.ZodObject<{
    sessionExpirationHours: z.ZodDefault<z.ZodNumber>;
    accommodationType: z.ZodDefault<z.ZodEnum<["capsule", "room", "house"]>>;
    defaultUserRole: z.ZodDefault<z.ZodEnum<["admin", "staff"]>>;
    maxGuestStayDays: z.ZodDefault<z.ZodNumber>;
    guideIntro: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideAddress: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideWifiName: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideWifiPassword: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideCheckin: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideOther: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideFaq: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideImportantReminders: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideHostelPhotosUrl: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, string | undefined, string | undefined>;
    guideGoogleMapsUrl: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, string | undefined, string | undefined>;
    guideCheckinVideoUrl: z.ZodEffects<z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, string | undefined>, string | undefined, string | undefined>;
    guideCheckinTime: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideCheckoutTime: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideDoorPassword: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideCustomStyles: z.ZodEffects<z.ZodOptional<z.ZodString>, string, string | undefined>;
    guideShowIntro: z.ZodDefault<z.ZodBoolean>;
    guideShowAddress: z.ZodDefault<z.ZodBoolean>;
    guideShowWifi: z.ZodDefault<z.ZodBoolean>;
    guideShowCheckin: z.ZodDefault<z.ZodBoolean>;
    guideShowOther: z.ZodDefault<z.ZodBoolean>;
    guideShowFaq: z.ZodDefault<z.ZodBoolean>;
    guideShowCapsuleIssues: z.ZodDefault<z.ZodBoolean>;
    guideShowSelfCheckinMessage: z.ZodDefault<z.ZodBoolean>;
    guideShowHostelPhotos: z.ZodDefault<z.ZodBoolean>;
    guideShowGoogleMaps: z.ZodDefault<z.ZodBoolean>;
    guideShowCheckinVideo: z.ZodDefault<z.ZodBoolean>;
    guideShowTimeAccess: z.ZodDefault<z.ZodBoolean>;
    defaultPaymentMethod: z.ZodDefault<z.ZodEnum<["cash", "tng", "bank", "platform"]>>;
    maxPaymentAmount: z.ZodDefault<z.ZodNumber>;
    totalCapsules: z.ZodDefault<z.ZodNumber>;
    capsuleSections: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    capsuleNumberFormat: z.ZodDefault<z.ZodString>;
    notificationRetentionDays: z.ZodDefault<z.ZodNumber>;
    cacheTimeMinutes: z.ZodDefault<z.ZodNumber>;
    queryRefreshIntervalSeconds: z.ZodDefault<z.ZodNumber>;
    defaultPageSize: z.ZodDefault<z.ZodNumber>;
    maxPageSize: z.ZodDefault<z.ZodNumber>;
    minGuestAge: z.ZodDefault<z.ZodNumber>;
    maxGuestAge: z.ZodDefault<z.ZodNumber>;
    showAllCapsules: z.ZodDefault<z.ZodBoolean>;
    defaultAdminEmail: z.ZodDefault<z.ZodString>;
    supportEmail: z.ZodDefault<z.ZodString>;
    supportPhone: z.ZodDefault<z.ZodString>;
    hostelName: z.ZodDefault<z.ZodString>;
    timezone: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    guideShowIntro: boolean;
    guideShowAddress: boolean;
    guideShowWifi: boolean;
    guideShowCheckin: boolean;
    guideShowOther: boolean;
    guideShowFaq: boolean;
    sessionExpirationHours: number;
    accommodationType: "capsule" | "room" | "house";
    defaultUserRole: "staff" | "admin";
    maxGuestStayDays: number;
    guideIntro: string;
    guideAddress: string;
    guideWifiName: string;
    guideWifiPassword: string;
    guideCheckin: string;
    guideOther: string;
    guideFaq: string;
    guideImportantReminders: string;
    guideCheckinTime: string;
    guideCheckoutTime: string;
    guideDoorPassword: string;
    guideCustomStyles: string;
    guideShowCapsuleIssues: boolean;
    guideShowSelfCheckinMessage: boolean;
    guideShowHostelPhotos: boolean;
    guideShowGoogleMaps: boolean;
    guideShowCheckinVideo: boolean;
    guideShowTimeAccess: boolean;
    defaultPaymentMethod: "cash" | "tng" | "bank" | "platform";
    maxPaymentAmount: number;
    totalCapsules: number;
    capsuleSections: string[];
    capsuleNumberFormat: string;
    notificationRetentionDays: number;
    cacheTimeMinutes: number;
    queryRefreshIntervalSeconds: number;
    defaultPageSize: number;
    maxPageSize: number;
    minGuestAge: number;
    maxGuestAge: number;
    showAllCapsules: boolean;
    defaultAdminEmail: string;
    supportEmail: string;
    supportPhone: string;
    hostelName: string;
    timezone: string;
    guideHostelPhotosUrl?: string | undefined;
    guideGoogleMapsUrl?: string | undefined;
    guideCheckinVideoUrl?: string | undefined;
}, {
    guideShowIntro?: boolean | undefined;
    guideShowAddress?: boolean | undefined;
    guideShowWifi?: boolean | undefined;
    guideShowCheckin?: boolean | undefined;
    guideShowOther?: boolean | undefined;
    guideShowFaq?: boolean | undefined;
    sessionExpirationHours?: number | undefined;
    accommodationType?: "capsule" | "room" | "house" | undefined;
    defaultUserRole?: "staff" | "admin" | undefined;
    maxGuestStayDays?: number | undefined;
    guideIntro?: string | undefined;
    guideAddress?: string | undefined;
    guideWifiName?: string | undefined;
    guideWifiPassword?: string | undefined;
    guideCheckin?: string | undefined;
    guideOther?: string | undefined;
    guideFaq?: string | undefined;
    guideImportantReminders?: string | undefined;
    guideHostelPhotosUrl?: string | undefined;
    guideGoogleMapsUrl?: string | undefined;
    guideCheckinVideoUrl?: string | undefined;
    guideCheckinTime?: string | undefined;
    guideCheckoutTime?: string | undefined;
    guideDoorPassword?: string | undefined;
    guideCustomStyles?: string | undefined;
    guideShowCapsuleIssues?: boolean | undefined;
    guideShowSelfCheckinMessage?: boolean | undefined;
    guideShowHostelPhotos?: boolean | undefined;
    guideShowGoogleMaps?: boolean | undefined;
    guideShowCheckinVideo?: boolean | undefined;
    guideShowTimeAccess?: boolean | undefined;
    defaultPaymentMethod?: "cash" | "tng" | "bank" | "platform" | undefined;
    maxPaymentAmount?: number | undefined;
    totalCapsules?: number | undefined;
    capsuleSections?: string[] | undefined;
    capsuleNumberFormat?: string | undefined;
    notificationRetentionDays?: number | undefined;
    cacheTimeMinutes?: number | undefined;
    queryRefreshIntervalSeconds?: number | undefined;
    defaultPageSize?: number | undefined;
    maxPageSize?: number | undefined;
    minGuestAge?: number | undefined;
    maxGuestAge?: number | undefined;
    showAllCapsules?: boolean | undefined;
    defaultAdminEmail?: string | undefined;
    supportEmail?: string | undefined;
    supportPhone?: string | undefined;
    hostelName?: string | undefined;
    timezone?: string | undefined;
}>;
export declare const phoneNumberSchema: z.ZodEffects<z.ZodString, string, string>;
export declare const emailSchema: z.ZodEffects<z.ZodString, string, string>;
export declare const capsuleNumberSchema: z.ZodEffects<z.ZodString, string, string>;
export declare const nameSchema: z.ZodEffects<z.ZodString, string, string>;
export declare const passwordStrengthSchema: z.ZodString;
export declare const malaysianICSchema: z.ZodEffects<z.ZodString, string, string>;
export declare const passportNumberSchema: z.ZodEffects<z.ZodString, string, string>;
export declare const ageSchema: z.ZodEffects<z.ZodString, string, string>;
export declare const checkoutDateSchema: z.ZodEffects<z.ZodString, string, string>;
export declare const paymentAmountSchema: z.ZodEffects<z.ZodString, string, string>;
export declare const bulkActionSchema: z.ZodObject<{
    ids: z.ZodArray<z.ZodString, "many">;
    action: z.ZodEnum<["delete", "archive", "activate", "deactivate"]>;
}, "strip", z.ZodTypeAny, {
    action: "delete" | "archive" | "activate" | "deactivate";
    ids: string[];
}, {
    action: "delete" | "archive" | "activate" | "deactivate";
    ids: string[];
}>;
export declare const searchQuerySchema: z.ZodEffects<z.ZodObject<{
    query: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodEnum<["active", "inactive", "all"]>>;
    dateFrom: z.ZodOptional<z.ZodString>;
    dateTo: z.ZodOptional<z.ZodString>;
    capsuleNumber: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
}, "strip", z.ZodTypeAny, {
    query?: string | undefined;
    capsuleNumber?: string | undefined;
    status?: "all" | "active" | "inactive" | undefined;
    dateFrom?: string | undefined;
    dateTo?: string | undefined;
}, {
    query?: string | undefined;
    capsuleNumber?: string | undefined;
    status?: "all" | "active" | "inactive" | undefined;
    dateFrom?: string | undefined;
    dateTo?: string | undefined;
}>, {
    query?: string | undefined;
    capsuleNumber?: string | undefined;
    status?: "all" | "active" | "inactive" | undefined;
    dateFrom?: string | undefined;
    dateTo?: string | undefined;
}, {
    query?: string | undefined;
    capsuleNumber?: string | undefined;
    status?: "all" | "active" | "inactive" | undefined;
    dateFrom?: string | undefined;
    dateTo?: string | undefined;
}>;
export declare const insertExpenseSchema: z.ZodObject<z.objectUtil.extendShape<Omit<any, "id" | "createdAt" | "updatedAt" | "createdBy">, {
    description: z.ZodEffects<z.ZodString, string, string>;
    amount: z.ZodEffects<z.ZodString, string, string>;
    category: z.ZodEnum<["salary", "utilities", "consumables", "maintenance", "equipment", "marketing", "operations", "other"]>;
    subcategory: z.ZodOptional<z.ZodString>;
    date: z.ZodEffects<z.ZodString, string, string>;
    notes: z.ZodOptional<z.ZodString>;
    receiptPhotoUrl: z.ZodOptional<z.ZodString>;
    itemPhotoUrl: z.ZodOptional<z.ZodString>;
}>, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    description?: unknown;
    amount?: unknown;
    category?: unknown;
    subcategory?: unknown;
    date?: unknown;
    notes?: unknown;
    receiptPhotoUrl?: unknown;
    itemPhotoUrl?: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    description?: unknown;
    amount?: unknown;
    category?: unknown;
    subcategory?: unknown;
    date?: unknown;
    notes?: unknown;
    receiptPhotoUrl?: unknown;
    itemPhotoUrl?: unknown;
}>;
export declare const updateExpenseSchema: z.ZodObject<z.objectUtil.extendShape<{
    [x: string]: z.ZodOptional<any>;
    [x: number]: z.ZodOptional<any>;
    [x: symbol]: z.ZodOptional<any>;
    description: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    amount: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    category: z.ZodOptional<z.ZodEnum<["salary", "utilities", "consumables", "maintenance", "equipment", "marketing", "operations", "other"]>>;
    subcategory: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    date: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    receiptPhotoUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    itemPhotoUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, {
    id: z.ZodString;
}>, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    description?: unknown;
    amount?: unknown;
    category?: unknown;
    subcategory?: unknown;
    date?: unknown;
    notes?: unknown;
    receiptPhotoUrl?: unknown;
    itemPhotoUrl?: unknown;
    id?: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    description?: unknown;
    amount?: unknown;
    category?: unknown;
    subcategory?: unknown;
    date?: unknown;
    notes?: unknown;
    receiptPhotoUrl?: unknown;
    itemPhotoUrl?: unknown;
    id?: unknown;
}>;
export declare const insertRainbowFeedbackSchema: z.ZodObject<z.objectUtil.extendShape<Omit<any, "id" | "createdAt">, {
    conversationId: z.ZodString;
    phoneNumber: z.ZodString;
    rating: z.ZodEffects<z.ZodNumber, 1 | -1, number>;
    feedbackText: z.ZodOptional<z.ZodString>;
}>, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    conversationId?: unknown;
    phoneNumber?: unknown;
    rating?: unknown;
    feedbackText?: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    conversationId?: unknown;
    phoneNumber?: unknown;
    rating?: unknown;
    feedbackText?: unknown;
}>;
export declare const updateFeedbackSettingsSchema: z.ZodObject<{
    enabled: z.ZodDefault<z.ZodBoolean>;
    frequency_minutes: z.ZodDefault<z.ZodNumber>;
    timeout_minutes: z.ZodDefault<z.ZodNumber>;
    skip_intents: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    prompts: z.ZodObject<{
        en: z.ZodDefault<z.ZodString>;
        ms: z.ZodDefault<z.ZodString>;
        zh: z.ZodDefault<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        en: string;
        ms: string;
        zh: string;
    }, {
        en?: string | undefined;
        ms?: string | undefined;
        zh?: string | undefined;
    }>;
}, "strip", z.ZodTypeAny, {
    enabled: boolean;
    frequency_minutes: number;
    timeout_minutes: number;
    skip_intents: string[];
    prompts: {
        en: string;
        ms: string;
        zh: string;
    };
}, {
    prompts: {
        en?: string | undefined;
        ms?: string | undefined;
        zh?: string | undefined;
    };
    enabled?: boolean | undefined;
    frequency_minutes?: number | undefined;
    timeout_minutes?: number | undefined;
    skip_intents?: string[] | undefined;
}>;
export declare const insertIntentPredictionSchema: z.ZodObject<z.objectUtil.extendShape<Omit<any, "id" | "createdAt">, {
    conversationId: z.ZodString;
    phoneNumber: z.ZodString;
    messageText: z.ZodString;
    predictedIntent: z.ZodString;
    confidence: z.ZodNumber;
    tier: z.ZodString;
}>, "strip", z.ZodTypeAny, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    conversationId?: unknown;
    phoneNumber?: unknown;
    messageText?: unknown;
    predictedIntent?: unknown;
    confidence?: unknown;
    tier?: unknown;
}, {
    [x: string]: any;
    [x: number]: unknown;
    [x: symbol]: unknown;
    conversationId?: unknown;
    phoneNumber?: unknown;
    messageText?: unknown;
    predictedIntent?: unknown;
    confidence?: unknown;
    tier?: unknown;
}>;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type UpdateUser = z.infer<typeof updateUserSchema>;
export type InsertGuest = z.infer<typeof insertGuestSchema>;
export type UpdateGuest = z.infer<typeof updateGuestSchema>;
export type CheckoutGuest = z.infer<typeof checkoutGuestSchema>;
export type InsertCapsule = z.infer<typeof insertCapsuleSchema>;
export type LoginRequest = z.infer<typeof loginSchema>;
export type CreateCapsuleProblem = z.infer<typeof createCapsuleProblemSchema>;
export type ResolveProblem = z.infer<typeof resolveProblemSchema>;
export type BulkGuestImport = z.infer<typeof bulkGuestImportSchema>;
export type BulkAction = z.infer<typeof bulkActionSchema>;
export type SearchQuery = z.infer<typeof searchQuerySchema>;
export type GuestSelfCheckin = z.infer<typeof guestSelfCheckinSchema>;
export type CreateToken = z.infer<typeof createTokenSchema>;
export type UpdateGuestTokenCapsule = z.infer<typeof updateGuestTokenCapsuleSchema>;
export type MarkCapsuleCleaned = z.infer<typeof markCapsuleCleanedSchema>;
export type UpdateSettings = z.infer<typeof updateSettingsSchema>;
export type InsertExpense = z.infer<typeof insertExpenseSchema>;
export type UpdateExpense = z.infer<typeof updateExpenseSchema>;
export type InsertRainbowFeedbackType = z.infer<typeof insertRainbowFeedbackSchema>;
export type UpdateFeedbackSettings = z.infer<typeof updateFeedbackSettingsSchema>;
export type InsertIntentPredictionType = z.infer<typeof insertIntentPredictionSchema>;
export interface PaginationParams {
    page?: number;
    limit?: number;
}
export interface PaginatedResponse<T> {
    data: T[];
    pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
        hasMore: boolean;
    };
}
export declare const validationUtils: {
    isValidEmail: (email: string) => boolean;
    isValidPhone: (phone: string) => boolean;
    isValidCapsuleNumber: (capsuleNumber: string) => boolean;
    isValidMalaysianIC: (ic: string) => boolean;
    isValidPassportNumber: (passport: string) => boolean;
    formatPhoneNumber: (phone: string) => string;
    formatName: (name: string) => string;
    sanitizeString: (str: string) => string;
};
